### ISSUE TITLE
ThemeProvider breaks build.  Listview deprecated error.

### ISSUE THREAD

**Issue by mdalpozzo** [robinpowered/glamorous-native#110]
- `glamorous-native` version: 1.4.2
- `react-native` version: 0.60.0
- `react` version: 16.8.6

Relevant code.

```javascript
import {ThemeProvider} from 'glamorous-native';

const theme = {
    main: {color: 'red'},
};


const App: React.FC<{}> = (): React.ReactElement => {
    return (
        <Provider store={store}>
            <ThemeProvider theme={theme}>
                <TestScreen />
            </ThemeProvider>
        </Provider>
    );
};

export default App;

```

What you did:
Wrapped react component with ThemeProvider and simple style object.

What happened:
errors:
ListView has been removed from React Native. See https://fb.me/nolistview for more information or use `deprecated-react-native-listview`.

Module AppRegistry is not a registered callable module (calling runApplication)

<img width="438" alt="Screen Shot 2019-07-12 at 4 40 19 PM" src="https://user-images.githubusercontent.com/26424381/61163597-cd36a800-a4c3-11e9-84c6-319b411fb20d.png">

Reproduction:
create react component wrapped in ThemeProvider from glamorous-native library and try to run either as ios or android

**Comment by FullstackJack** [comment]
Remove ListView and version bump.

**Comment by jdegger** [comment]
Try Emotion/Native

https://github.com/robinpowered/glamorous-native/issues/111
