### ISSUE TITLE
Support react-native-web

### ISSUE THREAD

**Issue by ajwhite** [robinpowered/glamorous-native#22]
After some interesting insights from @peggyrayzis [on twitter](https://twitter.com/peggyrayzis/status/865214734685044737), it would be worth exploring how this library performs with [react-native-web](https://github.com/necolas/react-native-web).

It's encouraged to understand:
- What changes would be needed for compatibility with the project? We currently depend on `react-native`'s components; does `react-native-web` shim itself in-place of `react-native`? Or do we need to be a bit less explicit with the dependence on `react-native`, and allow injecting the library?
- How does `glamorous-native` benchmark? A benchmarking project can be found here: https://github.com/necolas/react-native-web/tree/master/performance.
  

### Update

One incompatibility is currently known: 

https://github.com/robinpowered/glamorous-native/blob/9a7eea252b743b9c184f23a926ff2ddf07946395/src/is-style-prop.js#L17-L18

We depend on `ViewStylePropTypes` and `TextStylePropTypes` to determine, when `propsAreStyleOverrides = true`, if the prop should be registered as a component style. Example:

```js
<glamorous.View
  padding={20}
  backgroundColor="blue"
  someOtherProp={false}
/>
```

`padding` and `backgroundColor` would be picked up by `isStyleProp` and added to the components styling since they're part of the `ViewStylePropTypes` definition.

A pragmatic solution here would be to copy the values from `react-native` into this time, but I'd like to do something a bit more dynamic than that. Perhaps compile this project with those values pulled from `react-native` w/o needing to depend on `react-native` at runtime (as it will become polyfilled by `react-native-web`

**Comment by ajwhite** [comment]
Current thinking:

```js
// viewStylePropTypes.js


try {
  // load from RN if available
  module.exports = require('react-native/Libraries/Components/View/ViewStylePropTypes')
} catch (e) {
  // otherwise manually define
  module.exports = {
    ...
  }
}
```

**Comment by slorber** [comment]
Hi,

I'm trying to use glamorous-native with Gatsby, using RNW, without success.


My Gatsby conf is:

```js
exports.modifyWebpackConfig = ({ config, stage }) => {
  const program = {
    directory: __dirname,
    browserslist: ["> 1%", "last 2 versions", "IE >= 9"],
  };
  return generateBabelConfig(program, stage).then(babelConfig => {
    babelConfig.presets.push("babel-preset-react-native");
    const jsLoader = {
      test: /\.jsx?$/,
      exclude: modulePath => {
        return (
          /node_modules/.test(modulePath) &&
          !/node_modules\/(glamorous-native|react-native)/.test(modulePath)
        );
      },
      loader: `babel`,
      query: babelConfig,
    };
    config.removeLoader("js").loader("js",jsLoader);
    console.log("config",JSON.stringify(config,null,2));
  });
};
```

I have to transpile glamorous-native, but also the classes of RN as they are not transpiled.

As far as I understand, RNW does not try to replace your internal lib usage by RNW, but for web we must be able to run those RN internal code in the browser and to transpile it.

Unfortunatly it uses a global system for module resolution internally (haste?) and I get this error when trying to transpile this file:

[ViewStylePropTypes](https://github.com/facebook/react-native/blob/master/Libraries/Components/View/ViewStylePropTypes.js)

```
 ERROR  Failed to compile with 6 errors                                                                                                                                                               17:43:11

These dependencies were not found:

* ColorPropType in ./~/react-native/Libraries/Text/TextStylePropTypes.js, ./~/react-native/Libraries/Components/View/ViewStylePropTypes.js
* ViewStylePropTypes in ./~/react-native/Libraries/Text/TextStylePropTypes.js
* LayoutPropTypes in ./~/react-native/Libraries/Components/View/ViewStylePropTypes.js
* ShadowPropTypesIOS in ./~/react-native/Libraries/Components/View/ViewStylePropTypes.js
* TransformPropTypes in ./~/react-native/Libraries/Components/View/ViewStylePropTypes.js

To install them, you can run: npm install --save ColorPropType ViewStylePropTypes LayoutPropTypes ShadowPropTypesIOS TransformPropTypes
```


So this looks like complicated issue to solve in userland as it requires a quite complex transpilation setup to make it work imho.

What about removing the RN runtime peerDependency, and instead, adding a transpilation step for these 2 files into the glamorous-native itself? The idea is that you transpile the 2 RN files to generate source code that will be used inside glamorous-native.

The drawback is that you will tie glamorous-native to a specific version of RN regarding these 2 functions. As they don't evolve that much, not sure would be a big deal.

**Comment by ajwhite** [comment]
Hey @slorber, that's precisely what's holding the project back from RNW compatibility. The description of the issue also recommends we take a look at compiling the library with those two imports included.

I'd really like to be able to make the best of both worlds:
- Load `ViewStylePropTypes` and `TextStylePropTypes` if they're found by the dependant's dependencies
- And then fallback to loading a bundled copy of `ViewStylePropTypes` and `TextStylePropTypes` included in this library as a "fallback"

I'm not sure how to set up a bundler configuration to handle that, though. Would love some help!

**Comment by slorber** [comment]
It's possible to use babel macro plugins to import correct package at build time.

I've done it a bit here: https://expo.canny.io/feature-requests/p/ability-to-work-in-expo-client-after-detaching

![](https://canny.io/images/237340524fdda143adaf878fe303775e.png)

So basically, you would setup an env variable, so that when packaging for the web, and if this env variable is enabled, then you would require the local assets instead of the RN ones.

Not really liking this kind of env variable but I don't really see any other alternative. Maybe it could be set by RNW babel plugin so that all libs like this one could make usage of it if needed. cc @necolas

**Comment by necolas** [comment]
I don't see the benefit of using glamorous if you're using React Native. It's only going to make things slower and you can make your own module over RN with a similar API in a few lines of code

**Comment by slorber** [comment]
@necolas I guess it's a matter of taste. Personally I hate the separation of StyleSheet and View components in RN and really prefer to work with something akin to inline styles even if it's a bit less performant.

What do you mean by "you can make your own module over RN" ?

**Comment by ajwhite** [comment]
@ssomnoremac we'll likely do something similar to what you did with [RNStyles](https://github.com/hyrwork/glamorous-native/blob/54fd053c093687463afec8ccc8328e3fb13de4b1/index.js#L207-L297), but a couple differences:
- We'll need separation between `Text` and `View` styles, and ideally any styles that are tied to a specific type of component
- Would like to avoid maintaining our own collection, and instead pull them in from [ViewStylePropTypes](https://github.com/facebook/react-native/blob/master/Libraries/Components/View/ViewStylePropTypes.js) and [TextStylePropTypes](https://github.com/facebook/react-native/blob/master/Libraries/Text/TextStylePropTypes.js) directly.

The challenge here is that, with `react-native-web`, `react-native` is aliased to a set of polyfill components, where these files don't exist and cannot be imported. 

ideally we can bundle these definitions from `react-native` _at compile time_ and use them as a fallback if we're unable to import them from `react-native` _at run time_

**Comment by stephenhandley** [comment]
Any update available on the current state / prospects of this? Trying to evaluate the viability of using react-native-web to target components across platforms (i.e. mobile web app that can also be packaged with react native) and evaluating potential styling solutions there. Are there any other alternatives? Only thing I've found is https://github.com/tuckerconnelly/uranium
