### ISSUE TITLE
React native version support?

### ISSUE THREAD

**Issue by tabrindle** [robinpowered/glamorous-native#25]
No action is really necessary, except maybe to update documentation to say what version of RN it is written to be compatible with. There is no reasonable expectation that you should support older versions of a project that moves this fast, so there should just be a compatibility section. 

Yesterday there seemed to be an issue with RN 0.42.0 where it would red screen (but I can't reproduce it now) It seemed to resolve when we upgraded to 0.44.0

Otherwise, amazing work!

**Comment by ssomnoremac** [comment]
Yeah, it seems also you aren't supporting RN < 40.0 


Sucks for a lot of people with an in-market app like us 😞

**Comment by ssomnoremac** [comment]
Seems to be related to flatlist usage, which would make sense
<img width="337" alt="screen shot 2017-05-18 at 12 12 17 pm" src="https://cloud.githubusercontent.com/assets/3521359/26212356/4b7de8ac-3bc3-11e7-95f6-20baad692fce.png">

**Comment by ajwhite** [comment]
@ssomnoremac let's see what we can do about that. One of the challenges, as you see in your RSOD there, are the newer components that `glamorous-native` supports that aren't in earlier versions.

I think that we can lower the `peerDependency` to a common ground, and promote the usage of the component factory functions for the newer components in `0.42+`.

Thoughts? This would technically already be a breaking change

**Comment by ajwhite** [comment]
For example, over in [src/react-native-elements](https://github.com/robinpowered/glamorous-native/blob/17273cd1cc105988f5a6ffbfcb574e6c7c6d25a4/src/react-native-elements.js), we can avoid adding unsupported/nonexistent entries.

**Comment by ssomnoremac** [comment]
> So i think we can "test" to make sure the support exists

seems to be the way to go. I can certainly test out RN 37 as that's my version 😄

**Comment by ajwhite** [comment]
That'd be great @ssomnoremac, do you want to submit the fix?

**Comment by ssomnoremac** [comment]
Sure, I'll try to get to it tonight

**Comment by ajwhite** [comment]
Since it's a blocker for users who may want to use immediately, I have time right now that I can jump on it -- I will tag you in on the review
