### ISSUE TITLE
Touchable child must either be native or forward setNativeProps to a native component

### ISSUE THREAD

**Issue by alburdette619** [robinpowered/glamorous-native#28]
- `glamorous-native` version: 0.0.2
- `react-native` version: 0.44.0
- `react` version: 16.0.0-alpha.6

Relevant code.

```javascript
const StyledTouchableHighlight = glamorous.touchablehighlight(
  styles.defaults,
  {
    paddingVertical: 9,
    paddingHorizontal: 18,
  },
  (props) => {
    return {
      backgroundColor: colors(getButtonColorKey(props), 0, getAlpha(props)),
    };
  }
);

const StyledButtonText = glamorous.text(styles.defaults, styles.textDefaults, {
  color: 'white',
  fontWeight: '900',
});

const Button = (props) => {
  return (
    <StyledTouchableHighlight
      {...props}
      underlayColor={colors(getButtonColorKey(props), 1, getAlpha(props))}
    >
      <StyledButtonText>{props.text}</StyledButtonText>
    </StyledTouchableHighlight>
  );
};
```

What you did: I attempted to write a Button component using `glamorous.touchablehighlight` and `glamorous.text` with the latter being nested inside the former in order to style the button and its text.  I attempted to wrap this in a styled View from glamorous both by using `glamorous.view` and `const { View } = glamorous` but this returned the same error.  A native View wrapping the styled text had to be used to resolve the issue.

What happened: 

An error occurred:
```
Error: Touchable child must either be native or forward setNativeProps to a native component
    at invariant (invariant.js:44)
    at ensureComponentIsNative (ensureComponentIsNative.js:17)
    at Object.componentDidMount (TouchableHighlight.js:147)
    at Object.chainedFunction [as componentDidMount] (ReactClass.js:518)
    at ReactCompositeComponent.js:359
    at measureLifeCyclePerf (ReactCompositeComponent.js:63)
    at ReactCompositeComponent.js:358
    at CallbackQueue.notifyAll (CallbackQueue.js:75)
    at ReactNativeReconcileTransaction.close (ReactNativeReconcileTransaction.js:36)
    at ReactNativeReconcileTransaction.closeAll (Transaction.js:221)
```

Reproduction: 
1. Create a styled touchable component (I used TouchableHighlight, presumably any would work).
2. Create a styled text component
3. Create a component that has the styled touchable with the styled text (or any styled glamorous component) nested as its child.

Problem description: 

The glamorous-native version of TouchableHighlight does not apparently implement `setNativeProps`.  According to [this post in the docs](https://facebook.github.io/react-native/docs/direct-manipulation.html#composite-components-and-setnativeprops) this occurs because a glamorous component is not backed by a native view whose properties can be set in accordance with its touched state.  TouchableOpacity should have a similar issue.

Suggested solution:

I would start out by attempting to implement `setNativeProps` in `create-glamorous.js` in the `GlamorousComponent` class.

You could also look at [the fix for this by styled-components](https://github.com/facebook/react-native/issues/1040) to see how they fix it.

**Comment by ajwhite** [comment]
Great catch and report. Would you like to submit a PR for this fix?
