### ISSUE TITLE
Error while updating property in shadow node

### ISSUE THREAD

**Issue by schneck** [robinpowered/glamorous-native#50]
Hi there,

I have a problem augmenting a `<Row>` component from [react-native-easy-grid](https://github.com/GeekyAnts/react-native-easy-grid) with some custom styles.

My versions:

- `glamorous-native` version: 1.1.0
- `react-native` version: 0.44.2
- `react` version: 16.0.0-alpha.6

```javascript
import glamorous from 'glamorous-native';
import { Row } from 'react-native-easy-grid';

export const StyledRow = glamorous(Row)(props => ({
  marginLeft: props.margin ? 16 : 0,
}));
```
Usage:

```jsx
<StyledRow margin>[...]</StyledRow>
```
[](url)

What happened:

<img src="https://cloud.githubusercontent.com/assets/150785/26722067/c0e50ffe-478e-11e7-82cd-cc538aa96ca5.png" height="450" />

Any idea?

**Comment by ajwhite** [comment]
Interesting.. Can you verify that the following works if you were to style this normally?

```js
<Row style={{margin: 16}}>[...]</Row>
```

There seems to be a [lot going on](https://github.com/GeekyAnts/react-native-easy-grid/blob/master/Components/Row.js#L12-L24) when it comes to [computing properties](https://github.com/GeekyAnts/react-native-easy-grid/blob/master/Utils/computeProps.js) in that library.

Before diving into their code, I want to make sure that you can at least normally set a margin, such that doing so with `glamorous-native` yields an unexpected problem

**Comment by schneck** [comment]
It's running fine now - I made an upgrade to react 45.0, maybe it's related to this.
