### ISSUE TITLE
innerRef doesn't work with a glamorous(Component)

### ISSUE THREAD

**Issue by ColeTownsend** [robinpowered/glamorous-native#51]
- `glamorous-native` version: `^1.0.2`
- `react-native` version: custom build of `0.27.3`
- `react` version: `15.1.0`

This is largely a duplication of: https://github.com/styled-components/styled-components/issues/618

Relevant code.

```javascript
scrollToInput () {
      this.focusTimeout = setTimeout(() => {
        this.scrollView.getScrollResponder().scrollResponderScrollNativeHandleToKeyboard(
          ReactNative.findNodeHandle(this.textInput),
          120,
          true
        );
      }, 50);
 }

...

  <TextInput
              innerRef={component => this.textInput = component}
              value={team}
              returnKeyType={'next'}
              enablesReturnKeyAutomatically={true}
              autoCorrect={false}
              autoCapitalize={'none'}
              placeholder={I18n.t('pairing.team.placeholder')}
              textAlign="center"
              onFocus={() => this.scrollToInput()}
              onChangeText={text => onNameChange(text)}
              onSubmitEditing={onComplete}
/>
```

What you did:
Tapping the input triggers the `scrollToInput` function which requires the `ref` for the `ReactNative.findNodeHandle`

What happened:
![image](https://user-images.githubusercontent.com/987654/26845119-8897e7ce-4ac3-11e7-96b0-7cfddd746c4e.png)

Reproduction:
Create a `glamorous.textInput` and assign it an `innerRef` prop. Any sort of listener or interaction will error.

Problem description:
Glamorous-native components can handle `ref`'s but cannot handle `innerRef`'s. 

From [Phil's comment on the Styled Components repo](https://github.com/styled-components/styled-components/issues/618#issuecomment-289247967)
>  We would have to expose `innerRef` and the wrapped component would have to accept `innerRef` and pass it as `ref` to one of the children. Otherwise we'd have to check what it renders, clone it, and pass that on, which is not even good in terms of correctness, since the user might render more than one element anyway.

Suggested solution:
[Suggestions outlined here](https://github.com/styled-components/styled-components/issues/618#issuecomment-289247967)

**Comment by ajwhite** [comment]
Since this code sample is from a private project we both work on, I took a look at `TextInput` -- this is a HOC that we have defined in our project. It looks like with how we have it set up, it doesn't allow for `innerRef` to be passed through.

I'll take a look at a few more thing, but I'm 99% this is a non issue for `glamorous-native`
