### ISSUE TITLE
Exception on Text rendering

### ISSUE THREAD

**Issue by schneck** [robinpowered/glamorous-native#56]
Hi there,

I'm running into a problem when rendering a Text component.

Simple example:

**Component file:**
```
import glamorous from 'glamorous-native';
export const Headline = glamorous.text();
```
**In my parent component file:**

`            <Headline>Some error</Headline>
`

**Versions:**

- `glamorous-native` version: 1.1.0
- `react-native` version: 0.45.0
- `react` version: 16.0.0-alpha.12

**Result:**

<img src="https://user-images.githubusercontent.com/150785/27330360-5bd1bda4-55b9-11e7-80f4-26aeaa5cb0ea.png" height="450" />

**Comment by ajwhite** [comment]
Hey @schneck -- would you mind sharing a repository containing a sample of this problem? I wasn't able to reproduce this locally

**Comment by schneck** [comment]
Actually I think I found the issue. My glamorous component has a prop "theme":

```
Headline.propTypes = {
  theme: PropTypes.oneOf(['white', 'green', 'grey', 'darkgrey', 'error']),
};
```

When I omit it, it works.
