### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ajwhite** [robinpowered/glamorous-native#6]
It would be great to have a sibling icon for this project -- ideally a slight touch to the existing `glamorous` icon, perhaps with "native" text below it

References:

<img src="https://github.com/paypal/glamorous/blob/master/other/logo/full.png?raw=true" height="250" />

<img src="https://github.com/paypal/glamorous/blob/master/other/logo/compact.png?raw=true" height="250" />

cc @kentcdodds

**Comment by kentcdodds** [comment]
Based on [the website](https://facebook.github.io/react-native/) it seems that the React Native colors are higher contrast than the React colors. I wonder if we could make the glamorous-native logo be more dark? Even black? How's [this](https://codesandbox.io/s/59n6LMnJB)

<img width="449" alt="screen shot 2017-05-16 at 10 47 41 pm" src="https://cloud.githubusercontent.com/assets/1500684/26138890/b8d5575e-3a89-11e7-91de-6ce59be2b310.png">

**Comment by ajwhite** [comment]
I think this looks great - the colors line up with the site style of the site nicely 👍
