### ISSUE TITLE
How to prevent re-rendering

### ISSUE THREAD

**Issue by kay-is** [robinpowered/glamorous-native#62]
Hey,

I'm mostly using the JSX CSS props to create elements, but it seems that they will always be re-rendered.

Example:

```javascript
import React from "react";
import {View} from "glamorous-native";

const B = props =>
  <View backgroundColor={props.backgroundColor} height={200}/>;

class A extends React.Component {
  state = {i: 0};
  componentDidMount(){
    setInterval(() => this.setState(state => ({i: ++i})), 500)
  }
  render() {
    return <View height="100%"><B backgroundColor="red"/></View>;
  }
}
```

`B` will always re-render when the state of `A` is updated, even if it didn't change at all, probably because there will always be a new `"red"` string that isn't `===` to the last one.

Is there a way to let glamorous-native handle this or do I have to manage this by myself?

**Comment by ajwhite** [comment]
Forgive me if I'm wrong, but won't a `React.Component` (unlike a `React.PureComponent`) _always_ rerender if the parent renders unless it has a specific `shouldComponentUpdate` rule that can return `false`?

Also, any primitives (strings, bools, numbers) will be equal, unless they are objects:

![screen shot 2017-08-02 at 10 49 09 am](https://user-images.githubusercontent.com/656630/28879498-47892bf6-7770-11e7-9384-a93536fc737a.png)

**Comment by kay-is** [comment]
Good point.

I just thought I missed a huge performance problem here :)

**Comment by ajwhite** [comment]
Been there!

While on the topic, `React.PureComponent` will see if the _individual props_ (or state) has changed and only render if they have.

It would be interesting if we had a nice way to opt-into using a pure component.

Something like

```js
const MyPureStyledView = glamorous(el, {pure: true})({..})
```

Any opinions @kentcdodds?

**Comment by kentcdodds** [comment]
That sounds alright. We do have a `shouldClassNameUpdate` that I was thinking about using `{pure: true}` for eventually, but maybe that could be: `{pureClassName: true}` or something 🤔 

In any case, glamorous actually just uses the `withTheme` HoC for all glamorous components, so if we wanted to do this, we'd have to update the `withTheme` HoC to take an option like that. Which would be totally fine I think :smile:

**Comment by ajwhite** [comment]
_reopening for discussion purposes_

**Comment by kay-is** [comment]
I want

    import {View} from "glamorous-native/pure";

please.

Or maybe make it the default?

**Comment by ajwhite** [comment]
I think we need to be pretty liberal about how we control the render cycle. For instance, `context` subscriptions that lead to state changes, I _believe_, may not lead to renders if a parent has a `shouldComponentUpdate = () => false`. At the very least, it will need to be an opt-in

**Comment by ongmin** [comment]
Any updates on this?

**Comment by joelgetaction** [comment]
Any updates?
