### ISSUE TITLE
npm install failed 

### ISSUE THREAD

**Issue by REBOOTERS** [robinpowered/glamorous-native#69]
what I do :

```
git clone https://github.com/robinpowered/glamorous-native.git
cd glamorous-native/examples/react-native-glamorous
npm install

```
failed with error 

$ npm install
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t ssh://git@gith         ub.com/robinpowered/glamorous-native.git
npm ERR!
npm ERR! Warning: Permanently added 'github.com,192.30.255.113' (RSA) to the lis         t of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

**Comment by ajwhite** [comment]
Thanks for reporting this, it looks like we are using the [github repository as the dependency for our examples](https://github.com/robinpowered/glamorous-native/blob/1c74dbc4288b0f05ef8afc3e7fac78e9cef003c5/examples/react-native-glamorous/package.json#L10). This requires a key pair in order to install.

This should, instead, be a normal dependency. I think it was set up this way earlier on before `glamorous-native` had been published. Nice catch.

**Comment by ajwhite** [comment]
Would you like to make a PR that fixes this? You should be able to replace the `git` dependency with `1.1.2`

**Comment by REBOOTERS** [comment]
I change the git dependency with 1.1.2 

`{
	"name": "GlamorousNative",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"glamorous-native": "1.1.2",
		"react": "16.0.0-alpha.6",
		"react-native": "0.44.0"
	},
	"devDependencies": {
		"babel-jest": "20.0.1",
		"babel-preset-react-native": "1.9.2",
		"jest": "20.0.1",
		"react-test-renderer": "16.0.0-alpha.6"
	},
	"jest": {
		"preset": "react-native"
	}
}`

run the sample ,get the redbox error :

error: bundling: UnableToResolveError: Unable to resolve module `prop-types` fro
m `E:\2017-down-half\glamorous-native\examples\react-native-glamorous\node_modul
es\glamorous-native\src\react-compat.js`: Module does not exist in the module ma
p or in these directories:
  E:\2017-down-half\glamorous-native\examples\react-native-glamorous\node_module
s

This might be related to https://github.com/facebook/react-native/issues/4968

**Comment by andytompkins** [comment]
prop-types moved to its own package.
For me, the fix was as easy as adding prop-types to the example's package.json, but I am on npm5 and I am unsure if this would work for npm <= 2. How important is npm2 compat? If it is not critical, I can PR this easily.
