### ISSUE TITLE
Glamorous component does not render correctly

### ISSUE THREAD

**Issue by lindekaer** [robinpowered/glamorous-native#78]
- `glamorous-native` version: 1.2.0
- `react-native` version: 0.48.4
- `react` version: 16.0.0-alpha.12

What you did:
I tried to implement a simple <View> element as a "Glamorous component"

What happened:
The view is styled as follows:
```javascript
<View style={{ paddingTop: 8, paddingBottom: 8, backgroundColor: 'red' }}>
```

I decided to make a Glamorous component of it:
 ```javascript
import glamorous from 'glamorous-native'
const Wrapper = glamorous.view(
  {
    backgroundColor: 'red'
  },
  props => ({
    paddingTop: props.top ? props.gutter : 0,
    paddingRight: props.right ? props.gutter : 0,
    paddingBottom: props.bottom ? props.gutter : 0,
    paddingLeft: props.left ? props.gutter : 0
  })
)
```

That I then rendered as follows:
```javascript
<Wrapper gutter={8} top bottom>
// code ...
</Wrapper>
```
But I observed a difference in terms of a single pixel or two between the two implementations (see screenshots). When using the Glamorous component a few pixels are added to the top of the component breaking the layout.

**CORRECT** (using inline-styled View)
<img width="381" alt="incorrect" src="https://user-images.githubusercontent.com/4806217/31295607-79227e68-aadf-11e7-806f-61ab776c2880.png">

**INCORRECT** (using Glamorous component)
<img width="405" alt="correct" src="https://user-images.githubusercontent.com/4806217/31295606-79226658-aadf-11e7-9fd7-1d2a4911a991.png">

Reproduction:
Please see above description

**Comment by ajwhite** [comment]
That's.. very interesting. The only difference I can see between the "vanilla" and glamorous version would be that the glamorous component is a higher-order component of an underlying `View`.. But I still can't think of what could go wrong there.

Would you be able to reproduce this in a repository that you can share here?

**Comment by lindekaer** [comment]
Thanks for your reply @ajwhite! Here is the code for reproduce (in App.js on blank CRNA):

```javascript
import React from "react";
import { StyleSheet, Text, View } from "react-native";
import Glamorous from "glamorous-native";

const Wrapper = Glamorous.view(
  {
    backgroundColor: "red"
  },
  props => ({
    paddingTop: props.top ? props.gutter : 0,
    paddingRight: props.right ? props.gutter : 0,
    paddingBottom: props.bottom ? props.gutter : 0,
    paddingLeft: props.left ? props.gutter : 0
  })
);

export default class App extends React.Component {
  render() {
    return (
      <View>
        <View style={{ height: 100, backgroundColor: "black" }} />
        <View style={{ paddingTop: 8, paddingBottom: 8, backgroundColor: "red" }} >
          <Text>Inline style!</Text>
        </View>
        <View style={{ height: 100, backgroundColor: "black" }} />
        <Wrapper gutter={8} top bottom>
          <Text>Glamorous style!</Text>
        </Wrapper>
      </View>
    );
  }
}
```

**RESULT**
<img width="409" alt="screen shot 2017-10-06 at 22 16 17" src="https://user-images.githubusercontent.com/4806217/31296825-055b0752-aae4-11e7-9758-28c1ec7c5dc9.png">

**Comment by ajwhite** [comment]
Thanks @lindekaer - this'll do. I likely won't be able to take a look at this until next week, but thanks for providing all the information 💯

**Comment by duro** [comment]
@ajwhite Did this ever get looked at?

**Comment by ajwhite** [comment]
I have not, would love some help though!

**Comment by joshuakelly** [comment]
I bit of an update; It also happens `<Wrapper gutter={100} top left>` and `<Wrapper gutter={100} top right>` with the `1px` spacer on both of the declared sides. Does not happen on `<Wrapper gutter={100} top bottom>` top and bottom and will only stay on the top. Happens only on the bottom if one prop of `bottom` is declared.
