### ISSUE TITLE
<TouchableWithoutFeedback> onPress never fired when children is glamorous view

### ISSUE THREAD

**Issue by slorber** [robinpowered/glamorous-native#84]
When running inside Expo SDK 23 (RN50), if the children of a TouchableWithoutFeedback is a Glamorous View, the onPress callback is never fired.

This only happens in the js production build (the one you get with `exp publish`).

I have made a very simple repro case here: https://github.com/slorber/glamorous-bug/blob/master/App.js

The app is published on Expo here: https://expo.io/@slorber/glamorous-bug

In __DEV__, all 5 buttons are pressable, while in prod build, only 3 of them do work.

This is probably the same issue that I reported here with different symptoms: https://github.com/robinpowered/glamorous-native/issues/83

**Comment by ajwhite** [comment]
Man somethings up with some recent RN changes. I agree it sounds like a similar problem to #83. TouchableWithoutFeedback is suspect compared to the other touchables because it clones the child, rather the wrapping it in another View.

**Comment by ajwhite** [comment]
Fixed by #85
