### ISSUE TITLE
Media queries?

### ISSUE THREAD

**Issue by corysimmons** [robinpowered/glamorous-native#89]
Grepped project/docs for "media" and "query". Nothing. Just confirming no lib in RN has:

1. CSS to JS
2. Media queries

**Comment by ajwhite** [comment]
Hey @corysimmons, you're correct that there are no media queries in React Native.

We use [react-native-orientation](https://www.npmjs.com/package/react-native-orientation) to detect the orientation of the device and `Dimensions` from `react-native` to detect the width and height.

We take both of these things and add them to the `ThemeProvider` to access them in our glamorous components. I've been thinking about breaking this out and open sourcing them for the community. Here's an example of what the final version looks like for us:

```js
import {landscapeStyle, portraitStyle} from './utils/glamorous'

const ResponsiveView = glamorous.view(
  // style is applied when the device orientation is in landscape mode
  landscapestyle({backgroundColor: 'red'}),

  // style is applied when the device orientation is in portrait mode
  portraitStyle({backgroundColor: 'blue'})
)
```
