### ISSUE TITLE
Unexpected token import when testing with Jest + TypeScript

### ISSUE THREAD

**Issue by duro** [robinpowered/glamorous-native#92]
- `glamorous-native` version: 1.4.0
- `react-native` version: 0.55.2
- `react` version: 16.3.1

Relevant code.

```javascript
import G from 'glamorous-native'
```

What you did:

I am importing glamorous-native in a project that is being tested with Jest + TypeScript

What happened:

```
    /Users/adamduro/Workspace/projects/freebird/FreebirdNative/node_modules/glamorous-native/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import createGlamorous from './create-glamorous'
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

    > 1 | import G from 'glamorous-native'
      2 | import * as React from 'react'
      3 | import {
      4 |   BGImage,

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (src/components/ExploreCard/index.tsx:1:6043)
      at Object.<anonymous> (src/components/ExploreCard/index.spec.tsx:4:7)
```

Reproduction:

Use TypeScript + react-native (with `ts-jest`)

Problem description:

See above

Suggested solution:

It seems that glamorus-native does no pre-transpilation to it's npm package. I think this is where the problem lies. I cannot seem to get jest to transpile it for the test runner. Perhaps its a problem with my babel config.

Any suggestions are appreciated.

**Comment by ajwhite** [comment]
Hey @duro, thanks for opening the issue. I agree that publishing a transpiled bundle is a great idea for the project.

In the meantime, please take a look at the [Jest configuration](https://github.com/robinpowered/glamorous-native#jest-configuration) section of the README and let me know if that solves your issue.

**Comment by duro** [comment]
@ajwhite That did the trick. That said, I'm running up against a new config related issue that is not `glamorous-native` related. If you get a spare 5 minutes to look at it. I posted it over here:

kulshekhar/ts-jest/issues/492

Gotta be honest, setting up react-native + jest + typescript is proving far more challenging then I expected it to be.

**Comment by ajwhite** [comment]
Glad to hear you've got that resolved, and sorry to hear that it's been a struggle.

I've opened https://github.com/robinpowered/glamorous-native/issues/93 in light of this to bundle the library for `npm`
