### ISSUE TITLE
[question] how does this work?

### ISSUE THREAD

**Issue by vonovak** [robinpowered/glamorous-native#97]
hi! Sorry for the dumb issue title. I was reading through the docs and I'd like to ask about an example given in the readme:

> Oh, and what if you don't care to give MyStyledText a name? If you just want a text that's styled using StyleSheet? You can do that too:

```
const {Text} = glamorous;

function Section() {
  return (
    <Text
      fontSize={20}
      textAlign="center"
    >
      Hello world!
    </Text>
  )
}
```

Doing these kind of easy inline adjustments is what I miss in styled-components and I'm wondering - you say these styles are created using StyleSheet. Is there some sort of babel magic going on behind the scenes (doesn't seem to be the case) or are these styles created upon first render and then reused or...? Thanks!

**Comment by ajwhite** [comment]
Hey @vonovak,

These "prebuilts" are just [configured with the setting `propsAreStyleOverrides = true`](https://github.com/robinpowered/glamorous-native/blob/cd6001fbc4f13a0214ea924d634daa600c866821/src/index.js#L27). This allows you to specify style rules as properties (as you're already aware). 

The process is pretty simple -- it does not make use of `StyleSheet`, as they can change in the render method. No babel magic is used -- we just take those properties, and if they [are determined to be style rules](https://github.com/robinpowered/glamorous-native/blob/cd6001fbc4f13a0214ea924d634daa600c866821/src/is-style-prop.js#L46), then they are applied as _in line_ styles to the underlying component.

So in your example, it would end up generating:
```js
<Text style={{fontSize: 20, textAlign: 'center'}}>Hello world!</Text>
```

Hope that makes sense!

**Comment by slorber** [comment]
Hey, so you mean when this component renders twice, the styles are sent twice through the native bridge?

This is surprising me because I thought the lib was optimizing and creating stylesheets lazily, ie if it receives constant style props it would reuse the same stylesheet prop, like glamor does by hashing the inline style object to create a unique identifier

**Comment by ajwhite** [comment]
At the moment, only static styles, such as `margin` in this example, is registered as a stylesheet entry. Dynamic styles, such as padding above, are not, but a hashing strategy would be a great optimization

**Comment by slorber** [comment]
ok didn't know that.

I'll probably try to add this optimization sooner or later, taking some inspiration from Glamor should be helpful

**Comment by ajwhite** [comment]
Awesome @slorber!

**Comment by slorber** [comment]
Just for info, the StyleSheet API does not provide any optimisation.
I think it's not worth trying to do more optimizations until we know what RN team plan do to for optimizing styles over the bridge.

More context here: https://github.com/react-native-community/discussions-and-proposals/issues/64#issuecomment-444782831

**Comment by ajwhite** [comment]
Agreed @slorber -- glad you dropped those notes in on that thread 👍
